name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy"

      - name: cargo test
        run: cargo test --all-features

      - name: Run Clippy
        run: cargo clippy --all-features
