name: test suite
on: [ push, pull_request ]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy"

      - name: Test all features
        run: cargo test --all-features

      - name: Run Clippy
        run: cargo clippy --all-features

      - name: Test sync SCD30
        run: cargo test --features "sync, scd30"

      - name: Test async SCD30
        run: cargo test --features "async, scd30"

      - name: Test sync SCD40
        run: cargo test --features "sync, scd40"

      - name: Test async SCD40
        run: cargo test --features "async, scd40"

      - name: Test sync SCD41
        run: cargo test --features "sync, scd41"

      - name: Test async SCD41
        run: cargo test --features "async, scd41"

      - name: Build example - Synchronous SCD40
        working-directory: ./examples/embassy-scd40
        run: cargo build
